### ISSUE TITLE
Logging not working after updating to v1.8

### ISSUE THREAD

**Issue by Hoopex** [grkamil/laravel-telegram-logging#35]
```
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Class \"Logger\\TelegramHandler\" not found at /vendor/grkamil/laravel-telegram-logging/src/TelegramLogger.php:24)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Log/LogManager.php(247): Logger\\TelegramLogger->__invoke()
#1 /vendor/laravel/framework/src/Illuminate/Log/LogManager.php(220): Illuminate\\Log\\LogManager->createCustomDriver()
#2 /vendor/laravel/framework/src/Illuminate/Log/LogManager.php(135): Illuminate\\Log\\LogManager->resolve()
#3 /vendor/laravel/framework/src/Illuminate/Log/LogManager.php(122): Illuminate\\Log\\LogManager->get()
#4 /vendor/laravel/framework/src/Illuminate/Log/LogManager.php(645): Illuminate\\Log\\LogManager->driver()
#5 /vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): Illuminate\\Foundation\\Exceptions\\Handler->report()
#7 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(226): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#8 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#9 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#10 {main}
"} 
laravel.ERROR: Declaration of Logger\TelegramHandler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Logger\\TelegramHandler::write(array $record): void must be compatible with Monolog\\Handler\\AbstractProcessingHandler::write(Monolog\\LogRecord $record): void at /vendor/grkamil/laravel-telegram-logging/src/TelegramHandler.php:75)
[stacktrace]
#0 {main}
"} 
```

**Comment by grkamil** [comment]
Which laravel version do you use? I have checked, everything is okay. Maybe try to update v1.8.2

**Comment by Hoopex** [comment]
@grkamil 
I've debug the package and I found some issues (fixing them makes the package works again)

- TelegramHandler write function
$record param (type is not correct), I removed it

- Same class and formatText the params type is object but the function expect array
- Line 107 in the same class by somehow the condition it will be always true

Did i miss something ?

**Comment by grkamil** [comment]
Thank you, I have fixed for laravel v10
Try this one https://github.com/grkamil/laravel-telegram-logging/releases/tag/v1.9.0

**Comment by Hoopex** [comment]
Working like charm 👍, Thank you
